//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1142.0 using the following command:
// XmlSchemaClassGenerator.Console -n http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd=Actions.Nuget.Nuspec --nullable E:\nuspec.xsd
namespace Actions.Nuget.Nuspec {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dependency", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dependency {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("include")]
        public string Include { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("exclude")]
        public string Exclude { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dependencyGroup", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DependencyGroup {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dependency> _dependency;

        [System.Xml.Serialization.XmlElementAttribute("dependency")]
        public System.Collections.ObjectModel.Collection<Dependency> Dependency {
            get {
                return _dependency;
            }
            private set {
                _dependency = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Dependency collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DependencySpecified {
            get {
                return (this.Dependency.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DependencyGroup" /> class.</para>
        /// </summary>
        public DependencyGroup() {
            this._dependency = new System.Collections.ObjectModel.Collection<Dependency>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("targetFramework")]
        public string TargetFramework { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("reference", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Reference {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("file")]
        public string File { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contentFileEntries", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContentFileEntries {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("include")]
        public string Include { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("exclude")]
        public string Exclude { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("buildAction")]
        public string BuildAction { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("copyToOutput")]
        public bool CopyToOutputValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CopyToOutput property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CopyToOutputValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> CopyToOutput {
            get {
                if (this.CopyToOutputValueSpecified) {
                    return this.CopyToOutputValue;
                } else {
                    return null;
                }
            }
            set {
                this.CopyToOutputValue = value.GetValueOrDefault();
                this.CopyToOutputValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("flatten")]
        public bool FlattenValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Flatten property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool FlattenValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Flatten {
            get {
                if (this.FlattenValueSpecified) {
                    return this.FlattenValue;
                } else {
                    return null;
                }
            }
            set {
                this.FlattenValue = value.GetValueOrDefault();
                this.FlattenValueSpecified = value.HasValue;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("referenceGroup", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferenceGroup {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Reference> _reference;

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public System.Collections.ObjectModel.Collection<Reference> Reference {
            get {
                return _reference;
            }
            private set {
                _reference = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReferenceGroup" /> class.</para>
        /// </summary>
        public ReferenceGroup() {
            this._reference = new System.Collections.ObjectModel.Collection<Reference>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("targetFramework")]
        public string TargetFramework { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("frameworkReference", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkReference {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("frameworkReferenceGroup", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FrameworkReferenceGroup {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FrameworkReference> _frameworkReference;

        [System.Xml.Serialization.XmlElementAttribute("frameworkReference")]
        public System.Collections.ObjectModel.Collection<FrameworkReference> FrameworkReference {
            get {
                return _frameworkReference;
            }
            private set {
                _frameworkReference = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FrameworkReference collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrameworkReferenceSpecified {
            get {
                return (this.FrameworkReference.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FrameworkReferenceGroup" /> class.</para>
        /// </summary>
        public FrameworkReferenceGroup() {
            this._frameworkReference = new System.Collections.ObjectModel.Collection<FrameworkReference>();
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("targetFramework")]
        public string TargetFramework { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("package", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("package", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    public partial class Package {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("metadata")]
        public PackageMetadata Metadata { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageFilesFile> _files;

        [System.Xml.Serialization.XmlArrayAttribute("files", IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("file", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
        public System.Collections.ObjectModel.Collection<PackageFilesFile> Files {
            get {
                return _files;
            }
            private set {
                _files = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Files collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FilesSpecified {
            get {
                return (this.Files.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Package" /> class.</para>
        /// </summary>
        public Package() {
            this._files = new System.Collections.ObjectModel.Collection<PackageFilesFile>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadata", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadata {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public string Id { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("version")]
        public string Version { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("title")]
        public string Title { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("authors")]
        public string Authors { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("owners")]
        public string Owners { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("licenseUrl")]
        public string LicenseUrl { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("projectUrl")]
        public string ProjectUrl { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("iconUrl")]
        public string IconUrl { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("requireLicenseAcceptance")]
        public bool RequireLicenseAcceptanceValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RequireLicenseAcceptance property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RequireLicenseAcceptanceValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> RequireLicenseAcceptance {
            get {
                if (this.RequireLicenseAcceptanceValueSpecified) {
                    return this.RequireLicenseAcceptanceValue;
                } else {
                    return null;
                }
            }
            set {
                this.RequireLicenseAcceptanceValue = value.GetValueOrDefault();
                this.RequireLicenseAcceptanceValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("developmentDependency")]
        public bool DevelopmentDependencyValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DevelopmentDependency property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DevelopmentDependencyValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> DevelopmentDependency {
            get {
                if (this.DevelopmentDependencyValueSpecified) {
                    return this.DevelopmentDependencyValue;
                } else {
                    return null;
                }
            }
            set {
                this.DevelopmentDependencyValue = value.GetValueOrDefault();
                this.DevelopmentDependencyValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("summary")]
        public string Summary { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("releaseNotes")]
        public string ReleaseNotes { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("copyright")]
        public string Copyright { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _language = "en-US";

        [System.ComponentModel.DefaultValueAttribute("en-US")]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string Language {
            get {
                return _language;
            }
            set {
                _language = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("tags")]
        public string Tags { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("serviceable")]
        public bool ServiceableValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Serviceable property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ServiceableValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Serviceable {
            get {
                if (this.ServiceableValueSpecified) {
                    return this.ServiceableValue;
                } else {
                    return null;
                }
            }
            set {
                this.ServiceableValue = value.GetValueOrDefault();
                this.ServiceableValueSpecified = value.HasValue;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("icon")]
        public string Icon { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("readme")]
        public string Readme { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("repository")]
        public PackageMetadataRepository Repository { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("license")]
        public PackageMetadataLicense License { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType> _packageTypes;

        [System.Xml.Serialization.XmlArrayAttribute("packageTypes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("packageType", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
        public System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType> PackageTypes {
            get {
                return _packageTypes;
            }
            private set {
                _packageTypes = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PackageTypes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageTypesSpecified {
            get {
                return (this.PackageTypes.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadata" /> class.</para>
        /// </summary>
        public PackageMetadata() {
            this._packageTypes = new System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType>();
            this._frameworkAssemblies = new System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly>();
            this._frameworkReferences = new System.Collections.ObjectModel.Collection<FrameworkReferenceGroup>();
            this._contentFiles = new System.Collections.ObjectModel.Collection<ContentFileEntries>();
        }

        [System.Xml.Serialization.XmlElementAttribute("dependencies")]
        public PackageMetadataDependencies Dependencies { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly> _frameworkAssemblies;

        [System.Xml.Serialization.XmlArrayAttribute("frameworkAssemblies")]
        [System.Xml.Serialization.XmlArrayItemAttribute("frameworkAssembly", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
        public System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly> FrameworkAssemblies {
            get {
                return _frameworkAssemblies;
            }
            private set {
                _frameworkAssemblies = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FrameworkAssemblies collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrameworkAssembliesSpecified {
            get {
                return (this.FrameworkAssemblies.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FrameworkReferenceGroup> _frameworkReferences;

        [System.Xml.Serialization.XmlArrayAttribute("frameworkReferences")]
        [System.Xml.Serialization.XmlArrayItemAttribute("group", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
        public System.Collections.ObjectModel.Collection<FrameworkReferenceGroup> FrameworkReferences {
            get {
                return _frameworkReferences;
            }
            private set {
                _frameworkReferences = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FrameworkReferences collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrameworkReferencesSpecified {
            get {
                return (this.FrameworkReferences.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("references")]
        public PackageMetadataReferences References { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContentFileEntries> _contentFiles;

        [System.Xml.Serialization.XmlArrayAttribute("contentFiles")]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
        public System.Collections.ObjectModel.Collection<ContentFileEntries> ContentFiles {
            get {
                return _contentFiles;
            }
            private set {
                _contentFiles = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ContentFiles collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContentFilesSpecified {
            get {
                return (this.ContentFiles.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("minClientVersion")]
        public string MinClientVersion { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataRepository", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataRepository {

        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("url")]
        public string Url { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("branch")]
        public string Branch { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("commit")]
        public string Commit { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataLicense", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataLicense {

        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataPackageTypes", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataPackageTypes {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType> _packageType;

        [System.Xml.Serialization.XmlElementAttribute("packageType")]
        public System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType> PackageType {
            get {
                return _packageType;
            }
            private set {
                _packageType = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PackageType collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageTypeSpecified {
            get {
                return (this.PackageType.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataPackageTypes" /> class.</para>
        /// </summary>
        public PackageMetadataPackageTypes() {
            this._packageType = new System.Collections.ObjectModel.Collection<PackageMetadataPackageTypesPackageType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataPackageTypesPackageType", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataPackageTypesPackageType {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataDependencies", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataDependencies {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dependency> _dependency;

        [System.Xml.Serialization.XmlElementAttribute("dependency")]
        public System.Collections.ObjectModel.Collection<Dependency> Dependency {
            get {
                return _dependency;
            }
            private set {
                _dependency = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Dependency collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DependencySpecified {
            get {
                return (this.Dependency.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataDependencies" /> class.</para>
        /// </summary>
        public PackageMetadataDependencies() {
            this._dependency = new System.Collections.ObjectModel.Collection<Dependency>();
            this._group = new System.Collections.ObjectModel.Collection<DependencyGroup>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DependencyGroup> _group;

        [System.Xml.Serialization.XmlElementAttribute("group")]
        public System.Collections.ObjectModel.Collection<DependencyGroup> Group {
            get {
                return _group;
            }
            private set {
                _group = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Group collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupSpecified {
            get {
                return (this.Group.Count != 0);
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataFrameworkAssemblies", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataFrameworkAssemblies {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly> _frameworkAssembly;

        [System.Xml.Serialization.XmlElementAttribute("frameworkAssembly")]
        public System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly> FrameworkAssembly {
            get {
                return _frameworkAssembly;
            }
            private set {
                _frameworkAssembly = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FrameworkAssembly collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrameworkAssemblySpecified {
            get {
                return (this.FrameworkAssembly.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataFrameworkAssemblies" /> class.</para>
        /// </summary>
        public PackageMetadataFrameworkAssemblies() {
            this._frameworkAssembly = new System.Collections.ObjectModel.Collection<PackageMetadataFrameworkAssembliesFrameworkAssembly>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataFrameworkAssembliesFrameworkAssembly", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataFrameworkAssembliesFrameworkAssembly {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("assemblyName")]
        public string AssemblyName { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("targetFramework")]
        public string TargetFramework { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataFrameworkReferences", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataFrameworkReferences {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FrameworkReferenceGroup> _group;

        [System.Xml.Serialization.XmlElementAttribute("group")]
        public System.Collections.ObjectModel.Collection<FrameworkReferenceGroup> Group {
            get {
                return _group;
            }
            private set {
                _group = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Group collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupSpecified {
            get {
                return (this.Group.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataFrameworkReferences" /> class.</para>
        /// </summary>
        public PackageMetadataFrameworkReferences() {
            this._group = new System.Collections.ObjectModel.Collection<FrameworkReferenceGroup>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataReferences", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataReferences {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Reference> _reference;

        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public System.Collections.ObjectModel.Collection<Reference> Reference {
            get {
                return _reference;
            }
            private set {
                _reference = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Reference collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceSpecified {
            get {
                return (this.Reference.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataReferences" /> class.</para>
        /// </summary>
        public PackageMetadataReferences() {
            this._reference = new System.Collections.ObjectModel.Collection<Reference>();
            this._group = new System.Collections.ObjectModel.Collection<ReferenceGroup>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReferenceGroup> _group;

        [System.Xml.Serialization.XmlElementAttribute("group")]
        public System.Collections.ObjectModel.Collection<ReferenceGroup> Group {
            get {
                return _group;
            }
            private set {
                _group = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Group collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupSpecified {
            get {
                return (this.Group.Count != 0);
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageMetadataContentFiles", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageMetadataContentFiles {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContentFileEntries> _files;

        [System.Xml.Serialization.XmlElementAttribute("files")]
        public System.Collections.ObjectModel.Collection<ContentFileEntries> Files {
            get {
                return _files;
            }
            private set {
                _files = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Files collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FilesSpecified {
            get {
                return (this.Files.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageMetadataContentFiles" /> class.</para>
        /// </summary>
        public PackageMetadataContentFiles() {
            this._files = new System.Collections.ObjectModel.Collection<ContentFileEntries>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageFiles", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageFiles {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackageFilesFile> _file;

        [System.Xml.Serialization.XmlElementAttribute("file")]
        public System.Collections.ObjectModel.Collection<PackageFilesFile> File {
            get {
                return _file;
            }
            private set {
                _file = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the File collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSpecified {
            get {
                return (this.File.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackageFiles" /> class.</para>
        /// </summary>
        public PackageFiles() {
            this._file = new System.Collections.ObjectModel.Collection<PackageFilesFile>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1142.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackageFilesFile", Namespace = "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageFilesFile {

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        [System.Xml.Serialization.XmlAttributeAttribute("src")]
        public string Src { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("target")]
        public string Target { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("exclude")]
        public string Exclude { get; set; }
    }
}
